### ISSUE TITLE
Modules were resolved with conflicting cross-version suffixes in sbt plugin

### ISSUE THREAD

**Issue by igorfialko** [portable-scala/sbt-crossproject#123] opened 2020-01-11 13:59 UTC
## steps
sbt version:  1.3.4

## problem
Sub project which is an sbt module can not be compiled on 2.13.1. 
https://github.com/igorfialko/crossProjectBug

## expectation
It compiles fine in 2.13.1

## notes
https://github.com/sbt/sbt/issues/5360

```
[error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/fastparseIncompat/"), "projectB"):
[error]    com.lihaoyi:sourcecode _2.12, _2.13
[error]    com.lihaoyi:fastparse _2.13, _2.12
[error] stack trace is suppressed; run last projectB / update for the full output
[error] (projectB / update) Conflicting cross-version suffixes in: com.lihaoyi:sourcecode, com.lihaoyi:fastparse
```

**Comment by sjrd** [comment] 2020-01-11 22:53
An sbt plugin cannot compile on 2.13.x, since sbt and the sbt API are only compiled for 2.12.x.

Besides, this has nothing to do with sbt-crossproject. I'm pretty sure you could reproduce this with a normal `project`, so I'm going to close this issue here.

**Closed by sjrd** 2020-01-11 22:53 UTC

**Comment by igorfialko** [comment] 2020-01-12 13:00
@sjrd Thanks for the explanation!
